package testBox;

// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class GoogleSearchTestTest {

	public static void main(String[]args) {
		
		/*System.setProperty("webdriver.chrome.driver",
				"D:\\Selenium code\\selenium_testing\\resource\\driver\\chromedriver_win32\\chromedriver.exe");*/
		WebDriver driver;
		driver = new ChromeDriver();
		driver.get("https://www.google.com/");
		//driver.findElement(By.name("q")).click();
		driver.findElement(By.name("q")).sendKeys("selenium dev");
		driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
	}
}
